[package]
name = "load-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tulsa = { path = "../tulsa" }
tokio = { version = "1.29.1", features = ["rt-multi-thread"] }
