name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # Each feature flag combination. GitHub will run these in parallel because magic.
        features:
          - ""
          - "async_mode"
          - "use_dependencies"
          - "async_mode use_dependencies"

    steps:
    - uses: actions/checkout@v4
    - name: Setup protoc
      uses: arduino/setup-protoc@v2.0.0
    - name: Run tests
      run: |
        if [ -z "${{ matrix.features }}" ]; then
          cargo test --verbose
        else
          cargo test --verbose --features "${{ matrix.features }}"
        fi
