name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup protoc
      uses: arduino/setup-protoc@v2.0.0
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Test example-app with third-party libs
      run: cd app && cargo test --features use_dependencies --verbose
