name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup protoc
      uses: arduino/setup-protoc@v2.0.0
    - name: Build tulsa
      run: cd tulsa && cargo build --verbose
    - name: Test tulsa
      run: cd tulsa && cargo test --verbose
    - name: Build example-app
      run: cd example-app && cargo build --verbose
    - name: Test example-app with custom libs
      run: cd example-app && cargo test --verbose
    - name: Test example-app with third-party libs
      run: cd example-app && cargo test --features use_dependencies --verbose
